#pragma config(Motor,  port2,           FleftMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BleftMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FrightMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BrightMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(1==1)
	{

		//Lx is Ch1, Ly is Ch2, Ry is Ch3, Rx is Ch4
		motor(FleftMotor) = vexRT[Ch2];
		motor(BleftMotor) = vexRT[Ch2];
		motor(FrightMotor)= vexRT[Ch3];
		motor(BrightMotor)= vexRT[Ch3];

	}
}
