#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1==1)
	{
	//Motors
		motor[rightMotor] = vexRT[Ch2];
		motor[leftMotor] = vexRT[Ch3];

	//Arm
		if (vexRT[Btn6U])
			motor[armMotor] = 127;
		else if (vexRT[Btn6D])
			motor[armMotor] = -127;
		else if (!(vexRT[Btn6U] || vexRT[Btn6D]) )
			motor[armMotor] = 0;

	//Claw

	}

}
