#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rearMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------*\
|*	This is the code for the soccer bots, which have 2 omni wheels on		*|
|*	each side (each set linked to a single motor) and 1 on the back for *|
|*	steering, totaling 5.																								*|
|*																																			*|
|*	This program will use an adaptation of tank-style steering, where		*|
|*	the left and right joysticks control the left or right wheels on		*|
|*	the bot.
\*----------------------------------------------------------------------*/

const float rearMultiplier = 1; //This multiplier is used for the back wheel, to ensure that it is pivoting at a similar speed to the outside wheels.

task main()
{
	while(1==1)
	{
		motor(rightMotor) = vexRT[Ch2];	//Ch3 (joystick Ly) moves the right wheels forward and backwards.
		motor(leftMotor) = vexRT[Ch3];	//Ch2 (joystick Ry) moves the left 	wheels forward and backwards.

		motor(rearMotor) = (vexRT[Ch3] - vexRT[Ch2]) * rearMultiplier;	//The rear motor is used to help with pivoting, given by the difference between the left and right inputs
	}
		//robot:)
}
