#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rearMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------*\
|*	This is the code for the soccer bots, which have 2 omni wheels on		*|
|*	each side (each set linked to a single motor) and 1 on the back for *|
|*	steering, totaling 5.																								*|
|*																																			*|
|*	This program will use the left joystick for moving forward and			*|
|*	backwards with the left and right motors, and the right joystick		*|
|*	for turning left and right using the rear wheel.										*|
\*----------------------------------------------------------------------*/


task main()
{
	while(1==1)
	{
		motor(rightMotor) = vexRT[Ch3];	//Ch3 (joystick Ly) controls forward and backwards,
		motor(leftMotor) = vexRT[Ch3];	// using left and right wheels

		motor(rearMotor) = vexRT[Ch1];	//Ch1 (joystick Rx) controls rotating using rear motor
	}
}
